### About reduce_mean 

The functionality of numpy.mean and tensorflow.reduce_mean are the *same*

In [0]:
import numpy as np
import tensorflow as tf

In [13]:
c = np.array([[3.,4], [5.,6], [6.,7]])
print(c)

[[3. 4.]
 [5. 6.]
 [6. 7.]]


In [14]:
m1 = np.mean(c, 1) #axis=1 가로방향 =>방향지정
print(m1)

[3.5 5.5 6.5]


In [15]:
m3 = np.mean(c, 0) # axis=0 세로방향
print(m3)

[4.66666667 5.66666667]


In [16]:
m2 = tf.reduce_mean(c,1) #reduce_mean = 평균구하기
with tf.Session() as sess:
    result = sess.run(m2)
    print(result)

[3.5 5.5 6.5]
